### ISSUE TITLE
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'maxin-cn/Latte-1/'. Use `repo_type` argument if needed.

### ISSUE THREAD

**Issue by LukeLIN-web** [Vchitect/Latte#124]
Thank you for your effort.
`latte_diffusers.md` 

I tried `Inference with 4/8-bit quantization ` but failed.

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 402, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'maxin-cn/Latte-1/'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/share/quant.py", line 21, in <module>
    text_encoder = T5EncoderModel.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3247, in from_pretrained
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 466, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'maxin-cn/Latte-1/'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

**Comment by LukeLIN-web** [comment]
The line 19 should be `model_id = "maxin-cn/Latte-1"`

**Comment by maxin-cn** [comment]
Thanks! I will fix it.
