### ISSUE TITLE
Cannot find model：LatteT2V.from_pretrained_2d

### ISSUE THREAD

**Issue by bosima** [Vchitect/Latte#31]
```
~/Latte# bash sample/t2v.sh
/root/miniconda3/envs/latte/lib/python3.12/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/root/miniconda3/envs/latte/lib/python3.12/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "/root/Latte/sample/sample_t2v.py", line 160, in <module>
    main(OmegaConf.load(args.config))
  File "/root/Latte/sample/sample_t2v.py", line 30, in main
    transformer_model = get_models(args).to(device, dtype=torch.float16)
                        ^^^^^^^^^^^^^^^^
  File "/root/Latte/models/__init__.py", line 42, in get_models
    return LatteT2V.from_pretrained_2d(pretrained_model_path, subfolder="transformer")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Latte/models/latte_t2v.py", line 992, in from_pretrained_2d
    raise RuntimeError(f"{model_file} does not exist")
RuntimeError: None does not exist
```
Code:
```
        model = cls.from_config(config)
        
        model_files = [
            os.path.join(pretrained_model_path, 'diffusion_pytorch_model.bin'),
            os.path.join(pretrained_model_path, 'diffusion_pytorch_model.safetensors')
        ]

        model_file = None

        for fp in model_files:
            if os.path.exists(fp):
                model_file = fp

        if not model_file:
            raise RuntimeError(f"{model_file} does not exist")
```
the transformer does not have these two models：
<img width="748" alt="image" src="https://github.com/Vchitect/Latte/assets/6630893/1d2f8bda-286f-43dc-87f1-1a9f94a03249">

**Comment by bosima** [comment]
The local code is outdated.
