### ISSUE TITLE
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by likeatingcake** [Vchitect/Latte#61]
(latte) yueyc@super-AS-4124GS-TNR:~/Latte$ bash sample/ffs.sh
Using Ema!
WARNING: using half percision for inferencing!
  0%|                                                                                                                                                           | 0/250 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/yueyc/Latte/sample/sample.py", line 141, in <module>
    main(omega_conf)
  File "/home/yueyc/Latte/sample/sample.py", line 108, in main
    samples = diffusion.p_sample_loop(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/Latte/diffusion/gaussian_diffusion.py", line 454, in p_sample_loop
    for sample in self.p_sample_loop_progressive(
  File "/home/yueyc/Latte/diffusion/gaussian_diffusion.py", line 505, in p_sample_loop_progressive
    out = self.p_sample(
          ^^^^^^^^^^^^^^
  File "/home/yueyc/Latte/diffusion/gaussian_diffusion.py", line 406, in p_sample
    out = self.p_mean_variance(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/Latte/diffusion/respace.py", line 92, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/Latte/diffusion/gaussian_diffusion.py", line 279, in p_mean_variance
    model_output = model(x, t, **model_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/Latte/diffusion/respace.py", line 130, in __call__
    return self.model(x, new_ts, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/Latte/models/latte.py", line 330, in forward
    x = self.x_embedder(x) + self.pos_embed  
        ^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/anaconda3/envs/latte/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/anaconda3/envs/latte/lib/python3.11/site-packages/timm/layers/patch_embed.py", line 87, in forward
    x = self.proj(x)
        ^^^^^^^^^^^^
  File "/home/yueyc/anaconda3/envs/latte/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/anaconda3/envs/latte/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/anaconda3/envs/latte/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

这是我接触的第一个项目，可能会有很多问题求大家解答

**Comment by maxin-cn** [comment]
> slow_conv2d_cpu

Hi, thanks for your interest. Are you running this project on CPU? I haven't tried this project on CPU.

**Comment by likeatingcake** [comment]
> > 慢速_conv2d_cpu
> 
> 您好，感谢您的关注。你在CPU上运行这个项目吗？我还没有在CPU上尝试过这个项目。

您好，后来我改为在GPU上运行这个项目，成功解决了这个问题
